load("ext://helm_resource", "helm_repo")

helm_repo("bitnami", "https://charts.bitnami.com/bitnami", labels=["helm"])
helm_repo("kafka-ui-repo", "https://provectus.github.io/kafka-ui", labels=["helm"])
